### ISSUE TITLE
Fix StreamedMP skin title overlapping issue

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/MyAnime3#10]
**Reported by werndlymob, Jun 19, 2012**

Fix StreamedMP skin title overlapping issue

http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-12#post-875654

**Jun 21, 2012 werndlymob**

Actually, that's the part i fixed. The remaining two issues are 1. The episode title is cut too short, at least at 1080p, and 2. there's an overlay like a half circle and cylinder on top of the green highlight to show which episode is selected that shouldn't be there.

For the fix I did, all I did was drop the center column items down 20px below the central title.

**Comment by ElementalCrisis** [comment]
Unable to reproduce on current version, closing.
