### ISSUE TITLE
Plugin Version number is not updated

### ISSUE THREAD

**Issue by yhoogi** [japanesemediamanager/MyAnime3#29]
Plugin has been updated to 3.6.0.2 but in config file & logs the plugin is shown as 3.4.4.2
anime3.dll is also version 3.4.4.2
OS used is W10 64bit, btw.

MP Myanime3.log -file:
00000001 - 03.09.2016 13:41:03 - -------------------- SYSTEM INFO -----------------------
00000001 - 03.09.2016 13:41:03 - Plugin Version: v3.4.4.2
00000001 - 03.09.2016 13:41:03 - Operating System: Windows 10 32-bit
00000001 - 03.09.2016 13:41:03 - Screen Size: 1920x1080
00000001 - 03.09.2016 13:41:03 - Core: 1.15.0.0
00000001 - 03.09.2016 13:41:03 - MediaPortal: 1.15.0.0
00000001 - 03.09.2016 13:41:03 - ICSharpCode.SharpZipLib: 0.86.0.518 (0.85.5.452 or better recommended)
00000001 - 03.09.2016 13:41:03 - MediaInfo: 0.7.69.0 (0.7.20.0 or better recommended)
00000001 - 03.09.2016 13:41:03 - Base Folder: C:\Program Files (x86)\Team MediaPortal\MediaPortal
00000001 - 03.09.2016 13:41:03 - Skin Folder: C:\ProgramData\Team MediaPortal\MediaPortal\Skin
00000001 - 03.09.2016 13:41:03 - Plugins Folder: C:\Program Files (x86)\Team MediaPortal\MediaPortal\Plugins

**Comment by ElementalCrisis** [comment]
Ah yeah that's my fault, until compiling the latest version I had never used My Anime 3 so I'm sure I made some mistakes. I'll correct it and re-upload it.

**Comment by yhoogi** [comment]
Sorry,

Just seen your comment.
You still need support?

**Comment by ElementalCrisis** [comment]
With My Anime 3? Definitely. :)
