### ISSUE TITLE
"Continue Watching" from "Menu" gone in My Anime 3 - 3.6

### ISSUE THREAD

**Issue by nettosama** [japanesemediamanager/MyAnime3#30]
Updated to 3.6.0.2, and now the option on the menu to go directly to "Continue Watching" is gone. It helped jumping quickly to the episodes of each series that you can continue to watch from.

Checked using Titan skin.

**Comment by maxpiva** [comment]
Wont change, You can use the continue watching filter, at the main screen, we deprecated the previous Continue Watching, because we have to maintain an additional skin. And the previous funcionality is already in filters.

**Comment by nettosama** [comment]
Not even the same functionality. One takes you to the episode list after clicking the item, the other starts the "to watch" episode. But whatever.

**Comment by maxpiva** [comment]
Hmm, we might re-evaluate if we have more people capable of mantaining it

**Comment by RickDB** [comment]
Just restored this feature for Titan and tested working with it so created PR  :)

**Comment by nettosama** [comment]
Just pulled your PR, and it restores it correctly! Thank you.
