### ISSUE TITLE
3.6.0.4 uses wrong installation folder.

### ISSUE THREAD

**Issue by Andy2244** [japanesemediamanager/MyAnime3#32]
The 3.6.0.4 version installs itself into the wrong destination folders.

"Anime3.dll,Anime3.pdb,MA3_FFDShowAPI.dll,MA3_FFDShowAPI.pdb" are located directly under "c:\Program Files (x86)\Team MediaPortal\MediaPortal" instead of "c:\Program Files (x86)\Team MediaPortal\MediaPortal\plugins\Windows".

So for me the 3.6.0.4 version does not even show up in MP. The older versions did not have this problem.

The skins are also installed in the wrong folder: "C:\ProgramData\Team MediaPortal\MediaPortal\skin\\[DEFAULT]"> inside are the "Media" and "MyAnime3" folders. The skins folders like "Titan" do not have any MyAnime files installed at all. 

The installer itself will actually only install anything if "Avalon" is selected, otherwise it just states "clear cache" and won't install any files.

So how does the "MyAnime3-3.6.0.4.mpe1" build its install folder structure? The "[DEFAULT] string used as skin install folder, points to some problem detecting/parsing the folder structure?

**Comment by Andy2244** [comment]
Just did re-download the MyAnime3 plugin from the mainsite and noticed that my version was 6.9 MB, while the new one was 8.8 MB. Now the folders are correct, but you have to still checked "Avalon" or nothing will be installed. So only checking "Titan" will not install the skin/plugin.

**Comment by ElementalCrisis** [comment]
I'll look into it, the installer is the exact same one used for the previous release so this bug might have been present for awhile. 

On a side-note, I'm really not a fan of MediaPortal's extension installer. :)
