### ISSUE TITLE
Something Random Shows No Results

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#37]
Skin: Titan

Doesn't matter what you input, it returns nothing.

**Comment by ElementalCrisis** [comment]
Also it seems changing #Anime3.Random.Series.Category to #Anime3.Random.Series.Tag shows that string instead of the word Tag where it showed Category before.

**Comment by ElementalCrisis** [comment]
It does work when you're selecting a random series or episode from a group but not from your whole collection.

**Comment by RickDB** [comment]
Should work after PR#36 , the group filter wasn't being set and as a temporary fix made it the same as the context menu one which forwards the selected group.

**Comment by ElementalCrisis** [comment]
Just tried with latest build and works perfectly.
