### ISSUE TITLE
'Go to Episode List' option in 'Continue Watching' takes to group list instead of episode list

### ISSUE THREAD

**Issue by pandabuilder** [japanesemediamanager/MyAnime3#50]
'Go to Episode List' option in 'Continue Watching' takes to group list instead of episode list.

**Comment by maxpiva** [comment]
In Group Filters (first screen), that is normal. Since its a group filter.
In case Of the side menu continue watching, There is already work to bring
that functionality back.

**Comment by RickDB** [comment]
Hi @pandabuilder 

This is fixed in the latest release (3.6.10), only remaining problem should be the top left label with the title that doesn't get updated which will be fixed in the next release.
