### ISSUE TITLE
Calender Does Not Go Past October 15th

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#61]
![mediaportal_2016-10-06_02-42-00](https://cloud.githubusercontent.com/assets/9443295/19148375/45d19b4a-8b71-11e6-9a1b-55fa7e679ed3.png)

Just ends at October 15th, also doesn't seem to pull all the entries on AniDB either. 
http://anidb.net/perl-bin/animedb.pl?web=1&unknown=1&tvspecial=1&tvseries=1&show=calendar&ova=1&other=1&musicvideo=1&movie=1&last.anime.year=2016&last.anime.month=10&do.last.anime=Show&do=calendar

The only spot I found so far for the setting was in Desktop.

**Comment by RickDB** [comment]
Fixed in commit id 834cc13f77806a25a755627bcbf5af7271222f71

Now tries to load up to 6 months in advance, tested and for my current shows went up to December as there was nothing new after that.
