### ISSUE TITLE
Not All Relations Are Shown and String Issue

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#63]
![image](https://cloud.githubusercontent.com/assets/9443295/19150039/b2771880-8b79-11e6-8c65-b46e72c38e54.png)

**Comment by RickDB** [comment]
Fixed in commit id d43e351e6f1c006efb7b1457e000b36d66bd5969

Double checked a few other things in this window and made sure we skip invalid entries with no main title as well.
