### ISSUE TITLE
Seiyuu Does Not Show

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/MyAnime3#64]
![image](https://cloud.githubusercontent.com/assets/9443295/19150119/0f66c496-8b7a-11e6-9c53-e0a5a8e36e5b.png)

Should probably also say No Seiyuu Found for SERIES NAME.

**Comment by RickDB** [comment]
Fixed in commit cf37896bbfbc2486425f8d4e75194933fdfcfc45

Should follow the same logic as desktop now for naming, let me know if you spot issues with it :)
