### ISSUE TITLE
Shows series description for Avallonis

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/MyAnime3#7]
THX for the skinning - looking great - only (ah - yes - here it is ) - could you add a series description to the selection? So when you browse through the list you get the description at the bottom as scrolling text and if you have more than one season at the next page where you select the season? or maybe in a floating window positioned in the upper third of the fanart (probably this way it would also fit for coverflow and filmstrip)

When you use Filmsttrip or cover flow the test in teh middle (Groups - selection) is not readable probably it can be moved to the top of the Page?

**Comment by ElementalCrisis** [comment]
The Avallonis skin is no longer updated and thus support for it has been removed as for version 3.6.0.10.
